---
- hosts: config 
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: copy init
      copy: src=/home/ubuntu/directdemo2/config/playbooks/rsinit.js dest=/home/ubuntu
    - name: get mongo key 
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 0C49F3730359A14518585931BC711F9BA15703C6
        state: present
    - name: add mongo to sources list
      apt_repository: 
        repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse
        state: present
    - name: install mongo
      apt: name=mongodb-org update_cache=yes
    - name: remove bindIp
      lineinfile:
        regexp: 'bindIp.*'
        state: absent
        dest: /etc/mongod.conf
    - name: remove port 
      lineinfile:
        regexp: 'port.*'
        state: absent
        dest: /etc/mongod.conf
    - name: remove port 
      lineinfile:
        regexp: 'net.*'
        state: absent
        dest: /etc/mongod.conf

    - name: modify mongod conf for sharding
      blockinfile: 
        dest: /etc/mongod.conf
        block: |
          sharding:
            clusterRole: configsvr
          replication:
            replSetName: conf 
    - name: make mongo dir 2
      file: path=/var/lib/mongodb2 state=directory
    - name: make mongo dir 3
      file: path=/var/lib/mongodb3 state=directory
    - name: mongod1
      shell: mongod --fork --port 27017 --dbpath /var/lib/mongodb --logpath /home/ubuntu/mongo1 --configsvr --replSet conf
    - name: mongod2
      shell: mongod --fork --port 27018 --dbpath /var/lib/mongodb2 --logpath /home/ubuntu/mongo2 --configsvr --replSet conf
    - name: mongod3
      shell: mongod --fork --port 27019 --dbpath /var/lib/mongodb3 --logpath /home/ubuntu/mongo3 --configsvr --replSet conf
    - name: copy init
      copy: src=/home/ubuntu/directdemo2/config/init.js dest=/home/ubuntu/
    - name: init repl
      shell: mongo /home/ubuntu/init.js
